import { useState } from "react";
import api from "../api/client";
import type { AgentPublic } from "../types";
import type { SkinOut, SkinContent, StoreSkinOut } from "../api/skins";
import { DENSITY_LABELS, type TableDetail, type TableOut, type WeilanResponse } from "../api/weilan";
import { ACTION_LABELS, buildGameAction, type LegalAction } from "./gameActions";
import { ConfirmAction, FieldDialog, FieldForm, FieldFrame, FieldInput, FieldPanel, FieldSelect, FieldTabs, FieldText, ResourceState } from "./shared";
import { fieldTime, formText, useFieldResource } from "./fieldData";

export function WorkshopField() {
  const [tab, setTab] = useState("mine"); const [selected, setSelected] = useState<string | null>(null); const [editing, setEditing] = useState(false); const [code, setCode] = useState(""); const [message, setMessage] = useState("");
  const mine = useFieldResource<SkinOut[]>(tab === "mine" ? "/skins/mine" : null); const store = useFieldResource<StoreSkinOut[]>(tab === "store" ? "/skins/store" : null);
  const content = useFieldResource<SkinContent>(selected && tab === "mine" ? `/skins/${encodeURIComponent(selected)}/content` : null);
  // Fetch HTML as data, never execute it in the outer page.
  const preview = useFieldResource<string>(selected && tab === "store" ? `/skins/preview/${encodeURIComponent(selected)}` : null);
  function refresh(text: string) { setMessage(text); mine.refresh(); store.refresh(); }
  const sandbox = (html: string) => `<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; form-action 'none'; base-uri 'none'">${html}`;
  return <FieldFrame id="workshop"><FieldTabs options={{ mine: "我的作品", store: "作品展示" }} value={tab} onChange={v => { setTab(v); setSelected(null); setEditing(false); }} />{message && <p role="status">{message}</p>}<p className="field-notice">工坊管理自訂 HTML 作品。啟用狀態會保存至後端；目前寫實艙室不會被作品自動覆蓋。</p><FieldPanel title={tab === "mine" ? "我的工作台" : "社區作品"} action={<button onClick={() => { setSelected(null); setCode(""); setEditing(true); }}>建立作品</button>}><ResourceState resource={tab === "mine" ? mine : store} empty={(tab === "mine" ? mine.data : store.data)?.length === 0} /><div className="field-list">{mine.data?.map(s => <article className="field-item" key={s.id}><h3>{s.name}</h3><p>{s.is_active ? "已啟用" : "未啟用"} · {s.is_published ? "已發布" : "尚未發布"}</p><small>{fieldTime(s.updated_at ?? s.created_at)}</small><button onClick={() => setSelected(s.id)}>查看／編輯</button><div className="field-actions"><ConfirmAction title={s.is_active ? "停用這份作品" : "啟用這份作品"} action={() => api.post(s.is_active ? "/skins/deactivate" : `/skins/${encodeURIComponent(s.id)}/activate`)} onDone={() => refresh("啟用狀態已更新。")} /><ConfirmAction title={s.is_published ? "取消發布" : "送交作品審核"} action={() => api.post(`/skins/${encodeURIComponent(s.id)}/${s.is_published ? "unpublish" : "publish"}`)} onDone={() => refresh(s.is_published ? "已取消發布。" : "已送交審核；審核通過前不會出現在展示區。")} /><ConfirmAction title="刪除作品" action={() => api.delete(`/skins/${encodeURIComponent(s.id)}`)} onDone={() => refresh("作品已刪除。")} /></div></article>)}{store.data?.map(s => <article className="field-item" key={s.id}><h3>{s.name}</h3><small>{s.author_name} · {fieldTime(s.created_at)}</small><button onClick={() => setSelected(s.id)}>查看作品</button><ConfirmAction title="複製並啟用作品" action={async () => { const result = await api.post<SkinOut>(`/skins/${encodeURIComponent(s.id)}/apply`); setMessage(result.data.is_active ? "作品已複製並啟用；目前寫實艙室仍維持原本畫面。" : "作品已複製，但後端未確認啟用；請到我的作品檢查。"); }} onDone={() => { setTab("mine"); mine.refresh(); store.refresh(); }} /></article>)}</div></FieldPanel>
    {selected && !editing && <FieldDialog title="作品預覽" onClose={() => setSelected(null)}><ResourceState resource={tab === "mine" ? content : preview} />{(content.data || typeof preview.data === "string") && <div className="field-stack"><iframe className="field-preview-frame" title="隔離作品預覽" sandbox="" referrerPolicy="no-referrer" srcDoc={sandbox(content.data?.html_content ?? preview.data ?? "")} /><small>隔離預覽不執行腳本，外部圖片與樣式受限。</small>{content.data && <button onClick={() => { setCode(content.data!.html_content); setEditing(true); }}>編輯原始碼</button>}</div>}</FieldDialog>}
    {editing && <FieldDialog title={selected ? "編輯作品" : "建立作品"} onClose={() => setEditing(false)}><FieldForm label="保存作品" submit={data => api.request({ method: selected ? "PATCH" : "POST", url: selected ? `/skins/${encodeURIComponent(selected)}` : "/skins", data: { name: formText(data, "name"), html_content: code } })} onDone={() => { setEditing(false); setSelected(null); setTab("mine"); refresh("作品已保存。"); }}><FieldInput name="name" label="作品名稱" max={64} value={selected ? content.data?.name : undefined} /><label className="field-input">HTML 原始碼<textarea required maxLength={128000} value={code} onChange={e => setCode(e.target.value)} rows={10} /></label><iframe className="field-preview-frame" title="編輯中的隔離預覽" sandbox="" referrerPolicy="no-referrer" srcDoc={sandbox(code)} /><small>保存不等於發布，也不會自動啟用。</small></FieldForm></FieldDialog>}
  </FieldFrame>;
}

interface LiveTable extends TableDetail { status: string; status_name: string; turn_no: number; turn_agent_name: string | null }
interface TableMessage { id: string; agent_name: string | null; content: string; kind: string; created_at: string }
interface GameState { game: string | null; game_name?: string; message?: string; phase?: string; over?: boolean; result?: Record<string, unknown> | null; pending_players?: string[]; current_player?: string | null; view?: Record<string, unknown>; legal_actions?: LegalAction[] }
const VIEW_LABELS: Record<string, string> = { players: "玩家", colors: "棋色", turn: "輪到", phase: "階段", hands: "各玩家手牌", dealer: "莊家", values: "點數", alive: "仍在場", my_role_name: "我的身分", my_role: "我的角色", my_word: "我的詞語", wolves: "狼隊", seer_checks: "查驗結果", wolf_votes: "狼隊選擇", my_hand: "我的手牌", my_drawn: "剛摸到的牌", discards: "已出牌", wall_left: "牌牆剩餘", round: "回合", statements: "陳述", descriptions: "描述", votes: "投票", winners: "勝出者", winner: "勝方", notes: "念頭", sides: "正反方", topic: "主題", result: "結果", words: "詞語", spy: "臥底", roles: "身分", drawn: "已換牌", hand_counts: "手牌數", done: "已完成", last_discard: "上一張牌", how: "方式", from: "來源", player: "玩家", text: "內容", side: "方別" };
function ValueView({ value }: { value: unknown }) {
  if (value === null || value === undefined) return <span>—</span>;
  if (Array.isArray(value)) return <span>{value.length ? value.map((v, i) => <span key={i}><ValueView value={v} />{i < value.length - 1 ? " · " : ""}</span>) : "無"}</span>;
  if (typeof value === "object") return <dl>{Object.entries(value).map(([key, v]) => <div key={key}><dt><small>{VIEW_LABELS[key] ?? key}</small></dt><dd><ValueView value={v} /></dd></div>)}</dl>;
  return <span>{String(value)}</span>;
}
function GameControls({ game, tableId, refresh, announce }: { game: GameState; tableId: string; refresh: () => void; announce: (text: string) => void }) {
  const [choice, setChoice] = useState<[number, number] | null>(null);
  const view = game.view ?? {}; const actions = game.over ? [] : game.legal_actions ?? [];
  const board = Array.isArray(view.board) ? view.board as string[][] : null;
  const ownTiles = [...(Array.isArray(view.my_hand_raw) ? view.my_hand_raw.map(String) : []), ...(typeof view.my_drawn_raw === "string" ? [view.my_drawn_raw] : [])];
  return <div className="field-stack"><p>{game.game_name} · {game.phase ?? ""}{game.over ? " · 已結束" : ""}</p><small>目前輪到：{game.current_player ?? "多人／無"} · 等待：{game.pending_players?.join("、") || "無"}</small>{board && <div className="field-game-board" role="group" aria-label="五子棋盤，15 路">{board.map((row, r) => row.map((cell, c) => <button type="button" key={`${r}-${c}`} disabled={!!cell || !actions.some(a => a.type === "place")} aria-label={`第 ${r + 1} 行第 ${c + 1} 列${cell ? `，${cell}` : "，空格"}`} aria-pressed={choice?.[0] === r && choice?.[1] === c} onClick={() => setChoice([r, c])}>{cell === "black" ? "●" : cell === "white" ? "○" : cell ? "●" : choice?.[0] === r && choice?.[1] === c ? "+" : "·"}</button>))}</div>}
    <div className="field-item"><ValueView value={Object.fromEntries(Object.entries(view).filter(([key]) => !["board", "game", "phase", "turn", "result", "my_hand_raw", "my_drawn_raw", "moves"].includes(key)))} /></div>{game.over && <FieldPanel title="本局結果"><ValueView value={game.result} /></FieldPanel>}
    {!actions.length && !game.over && <p className="field-notice">目前沒有可執行的動作。等其他玩家後，按「更新桌況」。</p>}
    {actions.map((a, index) => ACTION_LABELS[a.type] ? <FieldForm key={`${game.phase}-${a.type}-${index}`} label={ACTION_LABELS[a.type]} submit={async data => { const result = await api.post<{ events?: string[]; over?: boolean }>(`/weilan/${encodeURIComponent(tableId)}/act`, { action: buildGameAction(a, data, view) }); announce(result.data.events?.join("；") || "動作已送出。"); }} onDone={() => { setChoice(null); refresh(); }}>
      {a.hint && <small>{a.hint}</small>}{["note", "statement", "describe"].includes(a.type) && <FieldText name="text" label={ACTION_LABELS[a.type]} />}
      {a.type === "place" && <><p>{choice ? `已選擇第 ${choice[0] + 1} 行、第 ${choice[1] + 1} 列；確認後才落子。` : "請先點選棋盤空格。"}</p><input type="hidden" name="row" value={choice?.[0] ?? ""} /><input type="hidden" name="col" value={choice?.[1] ?? ""} /></>}
      {a.type === "draw" && <div className="field-actions">{[0, 1, 2, 3, 4].map(i => <label key={i}><input type="checkbox" name="discard" value={i} />第 {i + 1} 張</label>)}</div>}
      {a.type === "discard" && <FieldSelect name="tile" label="選擇要出的手牌" options={Object.fromEntries(ownTiles.map(t => [t, t]))} />}
      {a.choices && <FieldSelect name="target" label="選擇目標" options={Object.fromEntries(a.choices.map(p => [p, p]))} />}{typeof a.side === "string" && <p>投給：{a.side === "pro" ? "正方" : "反方"}</p>}
    </FieldForm> : <p className="field-notice" key={index}>尚未支援的動作：{a.type}。請更新桌況，勿自行猜測操作。</p>)}
  </div>;
}
export function WeilanField() {
  const [density, setDensity] = useState("low"); const [selected, setSelected] = useState<string | null>(null); const [compose, setCompose] = useState(false); const [message, setMessage] = useState("");
  const list = useFieldResource<WeilanResponse>(`/weilan?density=${density}`); const mine = useFieldResource<AgentPublic | null>("/agents/mine");
  const table = useFieldResource<LiveTable>(selected ? `/weilan/${encodeURIComponent(selected)}` : null); const messages = useFieldResource<TableMessage[]>(selected ? `/weilan/${encodeURIComponent(selected)}/messages?limit=100` : null); const game = useFieldResource<GameState>(selected ? `/weilan/${encodeURIComponent(selected)}/game` : null);
  function refresh() { table.refresh(); messages.refresh(); game.refresh(); list.refresh(); }
  const seated = !!mine.data && !!table.data?.seats.some(s => s.agent_name === mine.data!.name); const host = !!mine.data && table.data?.host_name === mine.data.name;
  return <FieldFrame id="weilan"><FieldTabs options={DENSITY_LABELS} value={density} onChange={setDensity} />{message && <p role="status">{message}</p>}<FieldPanel title="找一張桌子" action={<button disabled={!list.data || !mine.data} onClick={() => setCompose(true)}>開一桌</button>}><ResourceState resource={list} empty={list.data?.tables.length === 0} /><ResourceState resource={mine} /><div className="field-list">{list.data?.tables.map(t => <article className="field-item" key={t.id}><h3>{t.title}</h3><p>{t.activity_name} · {t.host_name}</p><small>{t.current_seats} / {t.max_seats} 席</small><button onClick={() => setSelected(t.id)}>看看這一桌</button></article>)}</div></FieldPanel>
    {compose && <FieldDialog title="開一桌" onClose={() => setCompose(false)}><FieldForm label="確認開桌" submit={async data => { const r = await api.post<TableOut>("/weilan/open", { title: formText(data, "title"), activity_type: formText(data, "activity_type"), density, max_seats: Number(formText(data, "max_seats")) }); setSelected(r.data.id); }} onDone={() => { setCompose(false); setMessage("桌子已建立。"); list.refresh(); }}><FieldInput name="title" label="桌名" max={128} /><FieldSelect name="activity_type" label="活動" options={Object.fromEntries((list.data?.activity_types[density] ?? []).map(a => [a.key, a.name]))} /><FieldSelect name="max_seats" label="座位上限" options={Object.fromEntries([2, 3, 4, 6, 8, 12, 20].map(n => [String(n), `${n} 席`]))} value="6" /><small>實際開局人數依活動規則；五子棋兩人、獨坐一人、狼人殺至少四人。</small></FieldForm></FieldDialog>}
    {selected && !compose && <FieldDialog title="微瀾 · 桌邊" onClose={() => setSelected(null)}><div className="field-stack">{message && <p role="status">{message}</p>}<ResourceState resource={table} />{table.data && <><div className="field-row"><h3>{table.data.title}</h3><button onClick={refresh}>更新桌況</button></div><p>{table.data.activity_name} · {table.data.status_name || table.data.status} · 第 {table.data.turn_no} 回合</p><small>在座：{table.data.seats.map(s => s.agent_name).join("、") || "無"}</small><div className="field-actions">{!seated && table.data.is_active && <ConfirmAction title="加入這張桌子" action={() => api.post(`/weilan/${encodeURIComponent(selected)}/join`)} onDone={refresh} />}{seated && <ConfirmAction title="離席（進行中的遊戲會作廢）" action={() => api.post(`/weilan/${encodeURIComponent(selected)}/leave`)} onDone={refresh} />}{host && table.data.status === "waiting" && <ConfirmAction title="依目前在座玩家開局" action={() => api.post(`/weilan/${encodeURIComponent(selected)}/start`, { options: {} })} onDone={refresh} />}{host && table.data.is_active && <ConfirmAction title="關閉這張桌子" action={() => api.post(`/weilan/${encodeURIComponent(selected)}/close`)} onDone={() => { setSelected(null); list.refresh(); }} />}</div></>}
      <ResourceState resource={game} />{game.data?.game && <GameControls key={`${selected}-${table.data?.turn_no}`} game={game.data} tableId={selected} refresh={refresh} announce={setMessage} />}{game.data && !game.data.game && <p>{game.data.message}</p>}
      <ResourceState resource={messages} /><div className="field-chat">{messages.data?.map(m => <article className="field-bubble" key={m.id}><small>{m.agent_name ?? "系統"} · {fieldTime(m.created_at)}</small><p>{m.content}</p></article>)}</div>{seated && table.data?.is_active && <FieldForm key={messages.data?.length} label="送到桌邊" submit={data => api.post(`/weilan/${encodeURIComponent(selected)}/say`, { content: formText(data, "content") })} onDone={() => { setMessage("訊息已送出。"); messages.refresh(); }}><FieldText label="桌邊聊天" /></FieldForm>}
    </div></FieldDialog>}
  </FieldFrame>;
}
